#437 to add Role and Permission entities to a module
manaty/meveo pull request #501
Opened 2022-02-18 14:31 UTC by masumcse1

Problem 1. Following liquibase changlog file need to execute before meveo deployment in wildfy , but 
  this file was not executed  before meveo deployment. So, it makes error during deployment time.
 
 meveo-model/src/main/db_resources/changelog/current/structure.xml
 
 problem 2 : need to set some  value for "adm_role" table .I can not set those value. 
 
 Example: 
  update adm_role set creator='meveo.admin' , updater='meveo.admin'

 how can i represent those  value in structure.xml according to meveo development guideline ?
 
Another example  : 
   update adm_role set code=role_name , description=role_description 
  
  for unit testing purpose i was putted some data and it works fine.
  But How can i put real data for those two columns (code , description) or any importance to put real data 
  into table for this case ?

2022-02-18 15:22 UTC, ClementBareth commented
Problem 1 : the changeds needs to be append to the 7.0-structure.xml file. Then you just need to run liquibase:update -Padditional to execute them

2022-02-18 15:23 UTC, ClementBareth commented
The example values you provided are fine

2022-02-18 15:26 UTC, ClementBareth requested changes

2022-02-18 15:26 UTC, ClementBareth commented on meveo-api/src/main/java/org/meveo/api/PermissionApi.java
> +	public PermissionDto find(String code) throws EntityDoesNotExistsException, MissingParameterException
This needs to be implemented

2022-02-18 15:26 UTC, ClementBareth commented on meveo-api/src/main/java/org/meveo/api/PermissionApi.java
> +	public Permission createOrUpdate(PermissionDto dtoData) throws MeveoApiException, BusinessException {
This needs to be implemented

2022-02-18 15:26 UTC, ClementBareth commented on meveo-model/src/main/db_resources/changelog/current/structure.xml
> +	<changeSet author="Gulam Samdani" id="#437 -Convert to buss entity for adm_permission">
Move the changeset to 7.0-structure.xml

2022-02-18 15:28 UTC, ClementBareth commented
@masumcse1   In order to have the possibility to set the values, you need to add the not null constraint after setting the data, in another instruction. To set dynamically the data, you can use <sql> tag to write plain sql

2022-02-19 11:28 UTC, masumcse1 commented
problem1: PermissionApi.java

How many class attribute  need to consider for this permission entity creation method?
I have considered only two field : name , permission currently  where as this entity has several field.
I have added few attribute for this entity class .

problem2: PermissionApi.java

I have created two method (createOrUpdate,find) for Permission entity in this class . 
is there any necessary to implement those two function  in other class (PermissionRsImpl,PermissionRs) .

problem 3 : PermissionApi.java
I was not done any unit test for those two (createOrUpdate,find) method.
How can i do unit test for those two newly created method ?

problem3 : What is the request execution flow for bellow class ?

Example : 
....Api.java 
what is the  sequence are using for calling this class's method ? 

I have confusion but i seems that  sequence of function calling system is like

RS > WsImpl> API >API/ Service
JSFBean>API/Service>Service

2022-02-21 10:37 UTC, ClementBareth commented
Problem 1 => You can set name = description, and permission = code for now
Problem 2 => No, it's ok
Problem 3 => If you go to src/test/apiTests/postman/tests there are a lot of postman test suites that are used as unit /integration testing at the API level
Problem 4:
*  The REST sequence is RS >  API > API/ Service
* The JSF Sequence is correct

2022-02-21 10:41 UTC, ClementBareth requested changes

2022-02-21 10:41 UTC, ClementBareth commented on meveo-model/src/main/db_resources/changelog/releases/7.0-structure.xml
> +					</addColumn>
Here you miss following points : 

* Update of data in the table (for role : code = name, for permission, code = permission & description = name)
* Addition of unique / not null constraint on code

2022-02-21 11:39 UTC, masumcse1 commented
mvn liquibase:update -Padditional  

above command is not working  for meveo model.

![image](https://user-images.githubusercontent.com/9381810/154948157-426d97be-1770-4b1e-87c4-8744de91c502.png)

2022-02-21 15:02 UTC, ClementBareth requested changes

2022-02-21 15:02 UTC, ClementBareth commented on meveo-api/src/main/java/org/meveo/api/PermissionApi.java
> +		permissionService.create(permission);
Code & Description fields of the Permission entity also need to be filled

2022-02-21 15:02 UTC, ClementBareth commented on meveo-api/src/main/java/org/meveo/api/PermissionApi.java
> +		Permission permissionEntity = permissionService.findByPermission(permission);
Here use the code to retrieve the permission

2022-02-21 15:02 UTC, ClementBareth commented on meveo-api/src/main/java/org/meveo/api/PermissionApi.java
> +
Same remarks as create

2022-02-21 15:02 UTC, ClementBareth commented on meveo-model/src/main/db_resources/changelog/releases/7.0-structure.xml
> +
After the update you still need to add the constraints on code columns

2022-02-22 20:22 UTC, masumcse1 commented
i have created a new method "findByCode' in PermissionService. 

Please review my code.

2022-02-25 09:38 UTC, ClementBareth requested changes

2022-02-25 09:38 UTC, ClementBareth commented on meveo-model/src/main/db_resources/changelog/releases/7.0-structure.xml
> +	 </changeSet>
adm_role (code) should also be not null

2022-02-25 10:21 UTC, masumcse1 commented on meveo-model/src/main/db_resources/changelog/releases/7.0-structure.xml
> +	 </changeSet>
issue resolved .please check this code.

2022-02-25 14:29 UTC, ClementBareth approved these changes

2022-02-25 14:29 UTC, ClementBareth commented
@masumcse1 Can you merge master into your branch in order to resolve conflicts ?

2022-02-26 19:18 UTC, masumcse1 commented
Git  merge completed for this  branch.

2023-03-27 16:47 UTC, closed without merging