#662 add pre/post pull actions for module scripts
manaty/meveo pull request #685
Opened 2023-02-20 13:28 UTC by QuentinTixier

2023-02-20 13:37 UTC, ClementBareth requested changes

2023-02-20 13:37 UTC, ClementBareth commented on meveo-admin-ejbs/src/main/java/org/meveo/service/git/GitClient.java
> +        MeveoModule module = meveoModuleService.list().stream()
Here you will get some error because the git respository is not always linked to a module

2023-02-20 13:37 UTC, ClementBareth commented on meveo-admin-ejbs/src/main/java/org/meveo/service/git/GitClient.java
> +        MeveoModule module = meveoModuleService.list().stream()
By the way I'd prefer that you create an HQL query in the MeveoModuleService that take the git repository id as input

2023-02-20 13:37 UTC, ClementBareth commented on meveo-admin-ejbs/src/main/java/org/meveo/service/git/GitClient.java
> +				moduleScriptService.postPull(moduleScript, module);
Don't do this in the finally, but at then end of the try / catch block. The post pull should only be executed if the pull has been successfull

2023-02-20 14:28 UTC, QuentinTixier commented
timeSpent: 2

2023-02-20 16:05 UTC, ClementBareth requested changes

2023-02-20 16:05 UTC, ClementBareth commented on meveo-admin-ejbs/src/main/java/org/meveo/service/git/GitClient.java
> +			log.warn("Couldn't find module script, pull actions can't be executed");
Remove the warning

2023-02-22 09:45 UTC, ClementBareth requested changes

2023-02-22 09:45 UTC, ClementBareth commented on meveo-admin-ejbs/src/main/java/org/meveo/service/git/GitClient.java
> +        modulePrePull.fire(module);
@QuentinTixier don't throw the event if module is null

2023-02-22 09:45 UTC, ClementBareth commented on meveo-admin-ejbs/src/main/java/org/meveo/service/git/GitClient.java
> +        	modulePostPull.fire(module);
Same thing here

2023-02-22 10:00 UTC, ClementBareth approved these changes

2023-02-22 10:00 UTC, merged